--- #YAML:1.0
name:                Helix
version:             0.02
abstract:            web application framework.
license:             ~
author:              
    - Anton Belousov <abel@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Class::Accessor::Fast:         0
    DBI:                           0
    Exporter:                      0
    FindBin:                       0
    Getopt::Long:                  0
    List::Util:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
